main : Electro\BankUI\BankUI
name: BankUI
version: 1.0.0
api: 3.0.0
Author: Electro
depend: ["EconomyAPI"]

commands:
  bank:
    description: Baz Kardan Bank
    
permissions:
  bankui.admin:
    description: Permission to view other players transactions
    default: op
